# A. Import the dataset and add header columns with the names function

### We will start by importing the necessary libraries and loading the dataset. We will also add the header columns using the names function.

In [2]:
# Importing necessary libraries
import pandas as pd
import numpy as np

# Loading the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
df_wine = pd.read_csv(url, header=None)

# Adding header columns using names function
header = ['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium',
          'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
          'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']
df_wine.columns = header

# Checking out the data
print(df_wine.head())

   Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05  

# B. Split your data into training and testing sets using SciKit Learn's train_test_split function from model_selection

### We will split the dataset into training and testing sets using Scikit Learn's train_test_split function. We will also scale the data using StandardScaler.

In [5]:
# Importing necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Splitting the dataset into training and testing sets
X = df_wine.iloc[:, 1:].values
y = df_wine.iloc[:, 0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Scaling the data
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

##### We have split our data into training and testing sets and also scaled the data.

# C. Train your model using Scikit Learn’s estimator objects

### We will now create an instance of the MLPClassifier model and fit the training data to the model.

In [8]:
# Importing necessary libraries
from sklearn.neural_network import MLPClassifier

# Creating an instance of the model by defining the hidden_layer_sizes
mlp = MLPClassifier(hidden_layer_sizes=(10, ), max_iter=1000)

# Fitting the training data to the model
mlp.fit(X_train_std, y_train)

MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000)

#### We have created an instance of the MLPClassifier model and fitted the training data to the model.

# C. Use predict() method to get predictions

### We will now use the predict() method to get predictions and evaluate the model using the metrics from Scikit Learn.

In [11]:
# Importing necessary libraries
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Getting predictions
y_pred = mlp.predict(X_test_std)

# Evaluating the model
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

Accuracy: 0.9444444444444444
Confusion Matrix:
 [[19  0  0]
 [ 3 19  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           1       0.86      1.00      0.93        19
           2       1.00      0.86      0.93        22
           3       1.00      1.00      1.00        13

    accuracy                           0.94        54
   macro avg       0.95      0.95      0.95        54
weighted avg       0.95      0.94      0.94        54



#### We have used the predict() method to get predictions and evaluated the model using the metrics from Scikit Learn.

# D. Extract the MLP weights and biases after training your model

### We can extract the MLP weights and biases after training our model using the following code.

In [14]:
# Extracting the MLP weights and biases
print('Weights:\n', mlp.coefs_)
print('Biases:\n', mlp.intercepts_)

Weights:
 [array([[-0.03407473,  0.60154807, -0.30719651,  0.28700032, -0.53407631,
        -0.26214684,  0.54548037,  0.75223445, -0.31949134, -0.57364975],
       [ 0.64353562, -0.21250893, -0.2621765 ,  0.07225779,  0.03712934,
        -0.36878542,  0.12712994, -0.16458662,  0.17465559, -0.74299868],
       [ 0.8604302 ,  0.17929184,  0.46468487, -0.1773819 , -0.47346077,
        -0.18775879,  0.24489404,  0.13789538, -0.19920365, -0.18072353],
       [-0.06614041, -0.56791247,  0.34604089,  0.27868972,  0.47695058,
         0.12891431, -0.07058438, -0.59215002, -0.30556056,  0.44583613],
       [ 0.33432466,  0.38171636,  0.27483309,  0.30771578,  0.44125433,
        -0.72037223,  0.34178458,  0.3603608 , -0.05391372, -0.20470377],
       [-0.53866421,  0.3200375 , -0.50114844,  0.08776234, -0.61606155,
        -0.20738315,  0.07415085,  0.52257123, -0.13655225, -0.0283256 ],
       [ 0.1849579 ,  0.07262268,  0.17595735, -0.5014279 , -0.41748522,
        -0.0666111 , -0.5653757 , 

# We have successfully extracted the MLP weights and biases after training our model.